### ISSUE TITLE
Add Restaurant UI Fragment

### ISSUE THREAD

**Issue by BrianFenster** [cse442-fall-2019-offering/442projects-create-team-name#8]
I went to a restaurant not on the app that I liked. I add the restaurant to the app so other people can enjoy it. 

Task: Enter the credentials of a new restaurant to be added with a short description and potential tags such as type of cuisine, ambiance, price etc. 

Acceptance Test: Enter Name of Restaurant followed by address in the respective text fields. Enter description. Click on Submit button.

**Comment by jpearce185** [comment]
added text fields and submit button

**Comment by jpearce185** [comment]
Acceptance Test for UI:
[https://app.zenhub.com/files/206396413/69bc73b2-397f-4f8c-aed2-9323e8161a03/download](https://app.zenhub.com/files/206396413/69bc73b2-397f-4f8c-aed2-9323e8161a03/download)
